### ISSUE TITLE
Combining ClosureTable with eager loaded polymorphic models?

### ISSUE THREAD

**Issue by sjclemmy** [franzose/ClosureTable#130]
I'm creating a CMS and I'm using this library to record the hierarchy. I'm also using the concept of polymorphic relationships to encode the properties of model entities.
So I have a 'Content' model that uses the this library. In the Content model there is a content_id, a content_type.
I then have separate tables that represent the different models, e.g. 'Page', or 'Image' or 'Text'.
The model name and id are recorded in the content_type and content_id fields (respectively) in the 'Content' closure table.
I would like to be able to run the getDescendants() function and return not just the contents of the 'Content' closure table, but also the contents of the related model tables (Page, Image, etc).
I could do this by iterating over the results of the getDescendants() function, however I would like to eager load and get them in one query.
Is this currently possible? If not I think I'll try and fork this library to provide this functionality. 
Has anyone else come across trying to do this? Or is it not actually possible and I'd be heading down a dead end?

**Comment by hopewise** [comment]
@franzose so, did you have it working? or you still need to do manual work with descendants?
