### ISSUE TITLE
Не верный порядок миграций

### ISSUE THREAD

**Issue by greabock** [franzose/ClosureTable#131]
Сначала, я подумал что это глюк винды (OpenServer). Но проблема повторилась для меня и на линуске(VB). На чистом линуксе я, правда, не пробовал, но не думаю, что там что-то иначе.
Собственно, сама *Проблема:*
При создании миграций, время записи самих миграций (в имени файла) идентично. Далее они, по всей видимости, вызываются в алфавитном порядке. И тут мы получаем исключение - внешний ключ в таблице замыканий требует наличие таблицы сущностей. Приходится переименовывать миграцию с замыканиями на  "чуть-чуть попозже", и дампить автозагрузку заново. Вот такая история. 

Ну а сам пакет шикарен. Правда я не думал, что этот паттерн имеет отдельное название... всегда считал его частным случаем MP. Спасибо!

**Comment by franzose** [comment]
@greabock, в общем пока я тормозид, проблему решил чувак, который зареквестил поддержку Laravel 5, так что закрываю issue)))

**Comment by greabock** [comment]
=)

**Comment by girokon** [comment]
Хей, парни, а как же ветка dev-L4 ? там то осталась проблема =(

**Comment by franzose** [comment]
@girokon Балин, как можно скорее постараюсь сделать апдейт!
