### ISSUE TITLE
И снова те же грабли

### ISSUE THREAD

**Issue by greabock** [franzose/ClosureTable#135]
Привет! Прости, мне лень пилить коммит.
Тем временем, Тейлор и его дружки никак не успокоятся...

https://github.com/illuminate/database/commit/41102065e6abdf52ddf61853629a963501ecf9b9

Придется тоже скобочек добавить, теперь же массив по дефолсу ^_^.

**Comment by franzose** [comment]
Привет, сейчас поправлю. Какие-то еще ошибки есть? А то у меня 4 issue вроде висит, но объяснений того парня я не пойму...

**Comment by greabock** [comment]
У меня проблем не возникало... даже не знаю, он бы хоть стектрейс привел. Воспроизвел его пример - все работает. Что-то подсказывает, что он ловит ведьм не в той деревне.
