### ISSUE TITLE
demo setup

### ISSUE THREAD

**Issue by illuminate3** [franzose/ClosureTable#136]
HI,

I was wondering if you have a demo setup on stock L4.x?

Thanks!

**Comment by franzose** [comment]
Hi, @illuminate3! No, there's no demo setup. Do you think it would be a good idea?

**Comment by illuminate3** [comment]
For somebody like me who is trying to catch up to your level, Yes.

I tried to use your teapot repo but it uses lots of different design patterns and trying to revert back to vanilla Laravel app is becoming a learning experience. Which is good for me but having a Category/post/comment or even Category /post would be awesome since I could focus on learning 
ClosureTables. They really make lots of sense compared to nestedsets!

**Comment by franzose** [comment]
@illuminate3 Teapot is a ghost :) I started to code it and then stopped. I thought it might be a CMS written in Laravel but as we already have a number of them, I doubt it would make sense.

Okay, it seems a good reason to create such a demo git repo for ClosureTable. Thanks for suggestion! I've been thinking about writing an article about my library, but since its first release I've never got around it.

**Comment by illuminate3** [comment]
I figured that it was a ghost but it still has been a good piece of good for me to try to figure out.

@ demo
The main reason I asked about the demo is that I'm having trouble figuring out how to use your package.
I loaded it in a vanilla Laravel app and then used Jeffery Ways generators to create some simple CRUD for me.

I was following your readme and then added a 'name' field to the "pages" demo.  Store and Update don't work for me.

~~~
		$input = Input::all();
		$validation = Validator::make($input, Page::$rules);

		if ($validation->passes())
		{
			$this->page->create($input);
			return Redirect::route('pages.index');
		}
~~~

What should I be using?


Thanks!

**Comment by franzose** [comment]
@illuminate3 Hi, I have created [demo repository](http://github.com/franzose/ClosureTable-demo). I have just began to work on it, so there are no controllers or views at the time but I will add some CRUD stuff. Now there you can see model, repository, their tests (I'm not an expert on them though).

**Comment by illuminate3** [comment]
Thanks!
Will be watching and looking forward to your progression.
