### ISSUE TITLE
ranks

### ISSUE THREAD

**Issue by illuminate3** [franzose/ClosureTable#137]
I was wondering if this article is relevant to your package.
https://coderwall.com/p/lixing/closure-tables-for-browsing-trees-in-sql

Or have you already added that type of functionality into your package?

Thanks!

**Comment by franzose** [comment]
@illuminate3 My package uses closure table pattern along with the adjacency list. Once I decided to simplify SQL queries a bit and put `parent_id` to the entity table, so significant part of queries now simpler than if they used closure table pattern.

**Comment by illuminate3** [comment]
Ah, I see.
Thanks!

**Comment by franzose** [comment]
@illuminate3 I think that if there's a difference in complexity, there should be a difference in speed too.
