### ISSUE TITLE
Integrity constraint violation when deleting child objects

### ISSUE THREAD

**Issue by greggilbert** [franzose/ClosureTable#138]
Hey. This package is excellent, but I'm having an issue when deleting child objects.

I've tried it a number of ways, including:

```php
$unitToRemove = \Unit::find($id);
$parentUnit->removeChild($unitToRemove->position, true);
```
```php
$unitToRemove = \Unit::find($id);
$unitToRemove->deleteSubtree(true, true);
$parentUnit->removeChild($unitToRemove->position, true);
```
```php
$unitToRemove->delete();
```

and so on, but I get a violation:

```
"SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`database`.`unit_closure`, CONSTRAINT `unit_closure_ancestor_foreign` FOREIGN KEY (`ancestor`) REFERENCES `units` (`id`)) (SQL: delete from `units` where `parent_id` = 33 and `position` = 0)"
```

Presumably I'm doing something wrong here, but I'm not sure what. Any ideas?

---

Update: If I do the following, it works:

```php
$unitToRemove = \Unit::find($id);
\UnitClosure::where('descendant', '=', $id)->delete();
$unitToRemove->delete();
```

Looking at `deleteSubtree()`, it looks like it should be doing the same - but instead it seems to be looking up: `SELECT * FROM unit_closure WHERE ancestor = childId AND depth >= 0`, and then deleting that. But there's still a row in there that has parentId -> childId, and that row isn't getting deleted - so you get the constraint. I think that's right?

---

Update 2: Got a bit stuck, so I had to do this:

```php
$descendantIds = \UnitClosure::where('ancestor', '=', $removeId)->lists('descendant');
\UnitClosure::where('ancestor', '=', $removeId)->delete();
\UnitClosure::whereIn('descendant', $descendantIds)->delete();

$except = array_filter($descendantIds, function($id) use ($removeId) {
    return ($id !== $removeId);
});

\Unit::whereIn('id', $except)->delete();
\Unit::where('id', '=', $removeId)->delete();
```

So, delete the closure rows where the ID of the item to delete is the ancestor, and also where any of its descendants are the descendant. Then, since the item table has a parent_id reference, you have to delete the children first, and then the parent. So I filter out the descendant IDs for everything that's not the parent ID, delete those, and then delete the parent.

Not a lovely solution, but it works. Did I find a ridiculous backhanded way to pull this off and there's an easier solution, or does should this be worked in via pull request?

**Comment by majidphpdeveloper** [comment]
You should change your migration and add onDelete and onUpdate to cascade.
I had the same error.
and the reason is you should tell mysql about foreign key how to treat with your foreign keys.

**Comment by franzose** [comment]
@greggilbert @majidphpdeveloper Hi, guys! Greg, I don't quite understand how are you trying to remove child nodes: whole subtree or by one using `removeChild`? And could you clarify what specific piece of code causes that error?

**Comment by greggilbert** [comment]
@franzose I'm trying to outright delete a child node. The docs only mention `->removeChild()` or `->deleteSubtree()`, so I tried both. If that's not the right way to delete nodes, what is?

@majidphpdeveloper does have a good point that not having the delete/update cascades in place can cause issues.

**Comment by franzose** [comment]
@greggilbert Yes, it is the right way. I need to test it again myself.

**Comment by greggilbert** [comment]
Following up. Any word?

**Comment by franzose** [comment]
@greggilbert, @majidphpdeveloper I have also changed stub for entities' table migration. `parent_id` foreign key must have `onDelete('set null')`. That's was the problem with `removeChild` method.
