### ISSUE TITLE
links() function not working on getChildren output

### ISSUE THREAD

**Issue by majidphpdeveloper** [franzose/ClosureTable#139]
when we have a node and we use getChildren function to get this node children, the output of function is not capable of being paginate.
when I use links() function on output of getChildren() laravel says : 
Call to undefined method Franzose\ClosureTable\Extensions\Collection::links()

**Comment by franzose** [comment]
@majidphpdeveloper That's right because `links()` method belongs to `Pagination` not `Collection`.

**Comment by franzose** [comment]
@majidphpdeveloper At the time, the package does not provide a way to paginate results out of the box. You have to manually create `Pagination` object. This can be done by using protected `children` method. Something like so:
```php
public function getPaginatedChildren($limit, array $columns = [*])
{
    return $this->children()->paginate($limit);
}
```

The same applies to roots, ancestors and descendants.

**Comment by majidphpdeveloper** [comment]
thanks so much .

**Comment by franzose** [comment]
@majidphpdeveloper You're welcome! :)
