### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by laimisf** [franzose/ClosureTable#140]
Hi, <br>

does this package support **Laravel 5** or is it only for **Laravel 4**?

**Comment by franzose** [comment]
Hi, @laimisf! As of now (as far as I know) `php artisan closuretable:make` command might not work with the default options (however you can provide your own ones). All the rest must work, because there were no significant changes in Eloquent and QueryBuilder.

**Comment by franzose** [comment]
@laimisf, I plan to update the package for Laravel 5 and current version will be moved to another branch.

**Comment by laimisf** [comment]
@franzose, Thank You! <br>
I am going to use your package and waiting for renewal :)

**Comment by franzose** [comment]
@laimisf I think you can use it already. You just need to create models and migrations by hand.

**Comment by EspadaV8** [comment]
@laimisf I have a laravel 5 pull request open if you would to test it. If there are issues feel free to comment on it

https://github.com/franzose/ClosureTable/pull/143

**Comment by laimisf** [comment]
@EspadaV8 Thank You. But I chosen not to use this package at all after measuring my needs. Might use some day, but at the moment I am ok with the minimal solution I've written myself :)
