### ISSUE TITLE
Would it be a good idea to convert the classes to traits?

### ISSUE THREAD

**Issue by EspadaV8** [franzose/ClosureTable#147]
Laravel 5 supports PHP 5.4+ so moving the classes to traits wouldn't be an issue there.

Alas, I'm not clued in enough with the code to know exactly how to go about doing this. Looking at `ClosureTable` and `Entity` it seems that it would require a bit of a re-write (the c'tor and the static `boot` methods) and removal of some attributes (like timestamps and softdelete).

**Comment by franzose** [comment]
@EspadaV8 I have also thought about that but as of now, I don't have any clear idea.

**Comment by Malraoosh** [comment]
Yea, this would be much better, think about using it with User model which already extends `Authenticatable`

**Comment by fuzzybaird** [comment]
I am in agreement with @Malraoosh. I want to use this with my User Model, and I think a trait would be really convenient. I am struggling with this right now, and am forced to to have two models
```php
class User extends Authenticatable{
   public function tree()
   {
        return $this->hasOne(UserTree::class);
   }
}
```
Where `User` & `UserTree` Class both use the `users` table. I don't really love this, as I have to user the `UserTree` on all `create` methods and `User` on all authentication class.

**Comment by franzose** [comment]
I'll think about it, but currently I'd like to close the issue since there hasn't been any progress for three years already.
