### ISSUE TITLE
No way to check for children without hitting database

### ISSUE THREAD

**Issue by EspadaV8** [franzose/ClosureTable#150]
I was trying to use `::getTree()` to avoid hitting the database, however, with the current setup that's not possible.

Assuming we have a tree of posts

``` php
$posts = Post::getTree();
```

then in a template we want to create a nested unordered list we'd have to do something like the following

``` php
{{-- includes.post-list --}}
<ul>
@foreach ($posts as $post)
  <li>
    {{ $post->title }}
    @if ($post->hasChildren())
      @include('includes.post-list', ['posts' => $post->getChildren()])
    @endif
  </li>
@endforeach
```

Both the `hasChildren` and `getChildren` methods will hit the database, which shouldn't be needed. After calling `::getTree()` there is a relation set on the `Post` class called `children` that can be used like so

``` php
{{-- includes.post-list --}}
<ul>
@foreach ($posts as $post)
  <li>
    {{ $post->title }}
    @if ($post->children->count() > 0)
      @include('includes.post-list', ['posts' => $post->children])
    @endif
  </li>
@endforeach
```

However, this will fail the first time a post doesn't have any children because Laravel will attempt to call the `children()` method instead. It expects this to return a relationship, but instead it returns a `Builder` and then an exception is thrown.

The simple fix that I have at the moment is to change the index returned by `getChildrenRelationIndex()` to something else, e.g. `subnodes` and then you can do the following

``` php
{{-- includes.post-list --}}
<ul>
@foreach ($posts as $post)
  <li>
    {{ $post->title }}
    @if ($post->subnodes !== null && $post->subnodes->count() > 0)
      @include('includes.post-list', ['posts' => $post->children])
    @endif
  </li>
@endforeach
```

Doing the same kind of check (`$post->children !== null`) won't work because `children()` returns the `Builder`, which of course, isn't null.

`subnodes` isn't a great name, but I couldn't think of anything better right now.

I think a better solution, which might possibly fix #149 at the same time, would be to have `children()` return a relationship so that it can be handled like any other relationship within Laravel.

**Comment by moebaca** [comment]
Thank you for that code that you use up top:

```
@if ($post->hasChildren())
      @include('includes.post-list', ['posts' => $post->getChildren()])
@endif
```

I know it isn't the most efficient since it bangs the database, but hey, it works for now. When I tried to implement your fix for the 'subnodes' solution it broke everything.

Thanks again, saved me so much hair pulling.. actually I'm finding a lot of your stuff on here quite useful.
