### ISSUE TITLE
Unable to removeChild successfully. 

### ISSUE THREAD

**Issue by dbader87** [franzose/ClosureTable#151]
Hello, I've been running into key issue when using your library (using L4). When I run removeChild(0) method, it fails to delete the values in my many-to-many table as well as my main closure table. A foreign key constraint is causing this to happen, but I'm using the schema generated from the migration packaged with your software. I even tried removing the foreign keys, and the relationships still weren't removed. Can you shed some light on this issue? Should I be handling the detach on my own, or am I overlooking something? 

Everything else seems to be working as intended.

**Comment by EspadaV8** [comment]
I just tried the same thing and it worked without an issue for me (I'm using the L5 version, but nothing has changed with that between the 2 versions).

It deleted the child and removed the rows from the closure table.

Would it be possible to get a small test case created? Just an empty Laravel site with some seeding that shows the issue?

**Comment by dbader87** [comment]
Just as I suspected, it was something on my end. The model I was using needed to use the SoftDelete trait. Thanks for timely response.
