### ISSUE TITLE
getTree doesn't work when overriding 'parent_id'

### ISSUE THREAD

**Issue by amitaymolko** [franzose/ClosureTable#153]
Franzose\ClosureTable\Models\Entity.php

line 1077:         return $instance->orderBy('parent_id')->orderBy('position')
should be:                return $instance->orderBy($instance->getParentIdColumn())->orderBy($instance->getPositionColumn())

**Comment by EspadaV8** [comment]
@amitaymolko If this is still an issue then you can check out my fork here https://github.com/EspadaV8/ClosureTable/blob/master/src/EspadaV8/ClosureTable/Models/Entity.php#L1085

The column name has been moved out into a property of the class so you can easily change its name.

**Comment by franzose** [comment]
@amitaymolko I'm sorry for being late. This issue has been resolved.
