### ISSUE TITLE
Still being worked on?

### ISSUE THREAD

**Issue by EspadaV8** [franzose/ClosureTable#154]
Just wondering if this package is still being worked on or if other things in life have put it on hold for now

**Comment by franzose** [comment]
@EspadaV8 Thank you very much for the comments. I have no enough time at the moment to keep things in order. Your research (from another comment) is very appreciated!

**Comment by EspadaV8** [comment]
Thanks for getting back. Just wanted to check because I might release my fork then since it's likely I'll need to do a bit of work on things.

**Comment by franzose** [comment]
@EspadaV8 if you want, you can do a PR when you work is done. It would be great :)
