### ISSUE TITLE
Issues with hardcoded SQL and assuming ints

### ISSUE THREAD

**Issue by EspadaV8** [franzose/ClosureTable#155]
Just been trying to get this working on a DB that uses UUIDs instead of integers and coming across a number of issues.
- Ints are assumed in a number of places and will throw an exception if anything else is passed.
- The hardcoded SQL doesn't work with UUIDs because they are not escaped and produce invalid statements.

I'm having a look at fixing some of this up but just wanted to make a note of it here.

**Comment by franzose** [comment]
@EspadaV8 A year has passed... Recently I had a similar issue with UUIDs and I had to escape queries myself. So I think we could check arguments and if they are strings escape them. What do you think?

**Comment by EspadaV8** [comment]
@franzose I actually ended up working on this in my fork (https://github.com/EspadaV8/ClosureTable). We ended up removing the package with the plan to add it back again later on as an optimisation but never got around to it.

There are a number of commits to the master branch that deal with removing the hardcoded SQL with calls to eloquent methods. It's been a long time since I worked on it but it looks like these might be the more important commits

- Update SQL to use bindings - https://github.com/EspadaV8/ClosureTable/commit/b07f7828d2e47d413e71720041eb81ef5a289d37
- Remove `int` casts - https://github.com/EspadaV8/ClosureTable/commit/670d8afebbfa25bf3183ef4227f059fa61970624
- Removes SQL to use the eloquent model instead - https://github.com/EspadaV8/ClosureTable/commit/3599de43ff5f5396f4d426440cd53d9857cecdf9
- More SQL to eloquent model - https://github.com/EspadaV8/ClosureTable/commit/e167ce0a6ba12c0644244f3c903b25864ccb14be
- Final bit of SQL to eloquent queries - https://github.com/EspadaV8/ClosureTable/commit/e38379c1a6953e9ac4618c86ed0cd6fa1f88d601

I'm not sure how much those depend on other commits though, and I've no doubt that the code has changed since then so I doubt they could be cherry-picked.

Replacing the SQL with bindings or using an instance of the eloquent model both work well and remove the need to manually escape the UUIDs.

**Comment by franzose** [comment]
@EspadaV8 Great work, I'll dig into it soon. Did you try bindings or your changes on PostgreSQL? I tried to move to bindings but there were a buddy that reported errors occurring in PostgreSQL...

**Comment by EspadaV8** [comment]
Yeah, https://github.com/EspadaV8/ClosureTable/commit/b07f7828d2e47d413e71720041eb81ef5a289d37, that commit was the initial binding change. It worked for me when I wrote it, although I think that using eloquent models (https://github.com/EspadaV8/ClosureTable/commit/3599de43ff5f5396f4d426440cd53d9857cecdf9) is possibly a nice way to deal with it since it removes the need to have any SQL and should work across databases more consinstantly since it's just doing 2 simple inserts.

**Comment by franzose** [comment]
@EspadaV8 thank you very much for your work and excuse me for being silent on this issue for such a huge time. I highly appreciate your work.
