### ISSUE TITLE
getDescendantsTree() method missing

### ISSUE THREAD

**Issue by DanielAscher** [franzose/ClosureTable#157]
hi,
getDescendantsTree() is mentioned in the docs, but missing entirely in the code.

Used ->getDescendants()->toTree() instead, but if it's in the docs, it should be there.

Also sidenote: a small usage-example would be rather usefull for people using ClosureTable for the first time.

**Comment by franzose** [comment]
Hi, I have added two methods: `getAncestorsTree` and `getDescendantsTree`. Thanks for participation!
As for usage example: there's a separate repository called `ClosureTable-demo`. It uses Laravel 4 but I think that common practices would be clear.

**Comment by DanielAscher** [comment]
Thank you very much!

Did not know about the demo repository. Of course that is enough.
