### ISSUE TITLE
Get Children order_by

### ISSUE THREAD

**Issue by yokes-g-wiredelta** [franzose/ClosureTable#159]
Hi my dear Friends, I have an issues with the children category with order_by query, i'm using franzose/Closure plugin for category management i'm using follwing code

$furnitures = $Furnitures->getChildren();

Instead of above i need to use following code
$furnitures = $Furnitures->getChildren()->orderBy('category_position');

But it's showing error like below:
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR)
Call to undefined method Franzose\ClosureTable\Extensions\Collection::orderBy()
So please help me resolve this issue, there is any possibilities to get children with order_by Query Thanks in Advance

**Comment by franzose** [comment]
Hi, @yokeswar! If you need ordering children nodes, you can use `protected children()` method. It returns QueryBuilder, so you can write something like this:

```php
public function getChildrenWithOrdering($column, $order)
{
    return $this->children()->orderBy($column, $order)->get();
}
```

**Comment by yokeswar** [comment]
Thank you @franzose for quick reply, But the issues with Order_by Query What it's mean the Parameter $column and $order, and one more thing is the method getChildren() is only working, the children()  method is not working,can you explain it little bit elaborate?, Thanks in Advance

**Comment by zvermafia** [comment]
I think it will be like this `$furnitures = $Furnitures->children()->orderBy('category_position', 'ASC')->get();`

**Comment by franzose** [comment]
This is pretty, pretty old... But for those who are interested. ClosureTable 6 introduced a new one-to-many relation to children. Please, check the readme. It's used exactly as @zvermafia suggested.
