### ISSUE TITLE
Fix для laravel 5.2

### ISSUE THREAD

**Issue by kozlikov** [franzose/ClosureTable#161]
Пожалуйста, для laravel 5.2 сделайте фикс в классе:
Franzose\ClosureTable\Console\MakeCommand

Вместо: use Illuminate\Foundation\Composer;
Прописать: use Illuminate\Support\Composer;

Почему так: 
https://laravel.com/docs/5.2/upgrade

Composer Class

The Illuminate\Foundation\Support\Composer class has been moved to Illuminate\Support\Composer. This is unlikely to affect your application if you were not manually using this class.

**Comment by franzose** [comment]
@kozlikov уже прислали PR, я влил в master!

**Comment by kozlikov** [comment]
Спасибо!
