### ISSUE TITLE
A way of disabling global scope for getDescendants query

### ISSUE THREAD

**Issue by Noodlewitt** [franzose/ClosureTable#164]
Looking for a way of disabling some global scopes I have on my model, but doesn't seem to be possible to do with getDescendants method (and other methods that work in a similar way) I've had to hack it in for now, but a method of implementing this correctly would be appreciated

..so something like:
```
$root = Page::withoutGlobalScope(['live'])->find($id);
dd($root->withoutGlobalScope(['live'])->getDescendantsTree());
//..but obviously this doesn't work

**Comment by franzose** [comment]
Hi, @Noodlewitt! `withoutGlobalScope` returns instance of query builder, so you cannot have no access to model methods. As of now, I cannot say what exactly you can do with this.

**Comment by Noodlewitt** [comment]
so what I ended up doing was duplicating the method without the get at the end and returning that..

```
    //duplicate of Descendants without the ->get() at the end.
    public function collectDescendants(array $columns = ['*'])
    {
        return $this->joinClosureBy('descendant');
    }

```

This then allows me to call something like:
```
$tree->collectDescendants()->withoutGlobalScopes(['live'])->get()
```
works well for my purposes - might be better as a boolean parameter for getDescendents instead of a whole new method though. I guess it would also be good to have this on the other helper methods.. thoughts?

**Comment by franzose** [comment]
I think you can just wrap it up like this for all methods you need:
```php
public function getDescendantsWithoutGlobalScopes(array $scopes)
{
    return $this->joinClosureBy('descendant')->withoutGlobalScopes($scopes);
}
```
I think it's not a common use case, so I'd like to hear more opinios on this.

**Comment by Noodlewitt** [comment]
I guess my reason for allowing for the removal of the get is to allow for more complicated queries and possibly joins etc. I'd love to be able to do something like:

```php
$tree->collectDescendants()->join('content')->with('users')->where('...')->get()
//or whatever
```
But yeah, I agree my case is probably pretty edge case. Would be happy to submit a pull request for it though!

Awesome plugin btw
