### ISSUE TITLE
5.1 to 5.2 Breaking Change Composer Class

### ISSUE THREAD

**Issue by AadilC** [franzose/ClosureTable#166]
Hi there,

Upgrading to the latest release of ClosureTables v4.1 introduces breaking changes in the files

https://github.com/franzose/ClosureTable/blob/master/src/Franzose/ClosureTable/ClosureTableServiceProvider.php

and

https://github.com/franzose/ClosureTable/blob/master/src/Franzose/ClosureTable/Console/MakeCommand.php

they both include and use `Illuminate\Support\Composer` which has been moved in __Laravel 5.1 to 5.2__

Would in not be better in terms of compatibility to remove this class dependency completely?

__ClosureTableServiceProvider__ has the incorrect reference for __Laravel 5.2__
```php 
use Illuminate\Foundation\Composer;
```
while __MakeCommand__ has the correct reference for __Laravel 5.2__ but breaks code based on __Laravel 5.1__
```php 
use Illuminate\Support\Composer;
```
and furthermore sees only minimal usage

```php 
$this->composer->dumpAutoloads();
```

users can be encouraged to `php artisan dump-autoload` or `composer  dump-autoload` throught the docs

**Comment by franzose** [comment]
Hi, @AadilC! I made a new release, fixing `ClosureTableServiceProvider`. The master branch is for actual Laravel versions. Others are tagged accordingly.

**Comment by AadilC** [comment]
@franzose thanks for the prompt response and quick resolution.
I've updated my `composer.json` to target `"franzose/closure-table": "dev-L5.1"`

I really appreciate the effort you've put into this package, keep up the good work :+1:

**Comment by franzose** [comment]
@AadilC I'm glad to know that my lib is still useful for other developers! Happy coding! :)
