### ISSUE TITLE
ReflectionException after updating composer.json

### ISSUE THREAD

**Issue by mehranrasulian** [franzose/ClosureTable#171]
After updated ClosurTable from 4.0.1 to 4.1.1 i got an error:

``` bash
> composer update
> php artisan clear-compiled

  [ReflectionException]                             
  Class Illuminate\Support\Composer does not exist  

Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]  
  Error Output:
```

It seems Version 4.1.1 is for L5.2,
So i just chenged teh namespace of
`Illuminate\Support\Composer;`
to
Illuminate\Foundation\Composer;

And now above error will not appear again.

So you may consider a separate version for each other ?  Laravel 5.1 and Laravel 5.2  ?

**Comment by skygravity** [comment]
Error:
` [ReflectionException]
  Class Illuminate\Support\Composer does not exist`
Fix
vendor\franzose\ClosureTable\scr\Franzose\ClosureTable\Console\MakeCommand.php
line 6
from 
`use Illuminate\Support\Composer`
to
`use Illuminate\Foundation\Composer`
