### ISSUE TITLE
Reseting the tree.

### ISSUE THREAD

**Issue by naku-i386** [franzose/ClosureTable#172]
How would you approach this matter? To reset the whole tree i'm doing the following:
`$categories = Category::all();

```
    $count = $categories->count();

    for($i = 0; $i < $count; $i++){
        $categories[$i]->position = $i;
        $categories[$i]->makeRoot(0);
        $categories[$i]->save();
    }

    return redirect()->back();`
```

If i do it in foreach loop
`
foreach($categories as $c){
    $c->makeRoot(0);
}
`

Then very often when i move the branch or attempt to reset the tree it throws:

> SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(`ctables`.`categories`.`position` - 1)' (SQL: update `categories` set `position` = `position` - 1 where `parent_id` is null and `position` >= 0 and `id` <> 46 and `categories`.`deleted_at` is null)

`
public function move(Request $request){
        $this->validate($request,[
            'id' => 'required',
            'move_to' => 'required'
            ]);

```
    $child = Category::whereId($request->input('id'))->first();
    $parent = Category::whereId($request->input('move_to'))->first();

    if($child && $parent){

        $ids = [];

        if($child->hasDescendants()){
            $desc = $child->getDescendants();

            foreach($desc as $d){
                $ids[] = $d->id;
            }
        }

        if(!in_array($parent->id,$ids,true) && $parent->id != $child->id){
            $child->moveTo(0, $parent->id);
        }else{
            $child->makeRoot(0);
        }

    }

    return redirect()->back();
}`
```

`
for($i = 1; $i <= $count; $i++){
            $categories[$i]->makeRoot($i);
}
`

> Undefined offset: 13
> in Collection.php line 1098
> at HandleExceptions->handleError('8', 'Undefined offset: 13', '/usr/share/nginx/ctables/vendor/laravel/framework/src/Illuminate/Support/Collection.php', '1098', array('key' => '13')) in Collection.php line 1098

**Comment by franzose** [comment]
@naku-i386, I'm sorry for not answering you. But I didn't get the issue anyway. Feel free to reopen it and explain it to me in details if this kind of things is still relevant for you.
