### ISSUE TITLE
Counting the leaves of a node?

### ISSUE THREAD

**Issue by agougousis** [franzose/ClosureTable#173]
Hi! Is there any easy way to count the leaves that belong to a node's subtree?

**Comment by franzose** [comment]
Hi, @agougousis! I think you can do this using base model or trait. It's assumed that you put this into your ClosureTable model, not the Entity.

```php
/**
 * Count subtree leaves.
 *
 * @param int $ancestor
 * @return int
 */
public function countLeaves($ancestor)
{
    $table = $this->getTable() . ' as first';

    return $this->from($table)
        ->where('ancestor', $ancestor)
        ->where('depth', function($query) {
        $query->from($this->getTable() . ' as second')
            ->whereRaw('first.ancestor = second.ancestor')
            ->max('depth');
    })->count();
}
```

**Comment by agougousis** [comment]
It throws an error:  Column not found: 1054 Unknown column 'first.ancestor' in 'where clause'...
Since, I am not that familiar with building subqueries in Laravel, I added the following raw query to the model which returns the leaves under that node:

public function getNodeLeaves(){
        $primary = $this->getQualifiedKeyName();
        $closure = $this->closure->getTable();
        $ancestor = $this->closure->getQualifiedAncestorColumn();
        $descendant = $this->closure->getQualifiedDescendantColumn();    
        
        $query = DB::select("select $ancestor from $closure where $descendant in (select $descendant from $closure where $ancestor = ".$this->getKey().") group by $ancestor having max(depth) = 0");
        
        return $query;
    }
