### ISSUE TITLE
Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by ajay-logiciel** [franzose/ClosureTable#174]
I am using Clouser Table for managing directories file structure. this following issue occurred when i trying to add multiple child one by one with multiple request at a time.

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (SQL:             INSERT INTO resource_closure (ancestor, descendant, depth)            SELECT tbl.ancestor, 40933, tbl.depth+1            FROM resource_closure AS tbl            WHERE tbl.descendant = 40933            UNION ALL            SELECT 40933, 40933, 0

**Comment by moebaca** [comment]
I got this as well with multiple users using my app at once.

**Comment by franzose** [comment]
@ajay-logiciel, @moebaca It seems it is an issue with InnoDB. I've found a couple of posts on StackOverflow and Github, covering this issue:

https://github.com/laravel/framework/issues/5380
https://stackoverflow.com/a/2423921/388783

**Comment by franzose** [comment]
@ajay-logiciel, @moebaca It seems that Laravel 5.3 already comes with ‘reattempted’ transactions. What do you think of using this feature in the library?

https://github.com/laravel/framework/pull/14931/commits/bdfc61b308298cd47e686dc5dd45c83188213f39

**Comment by moebaca** [comment]
Thanks franzose, I was actually reading those earlier.

I've decided to take a different approach to how I was doing it before. I am going to have any mutations to the closure_table be done in queued jobs. That way I never have two people accessing the table at a given time, thus preventing deadlocks.

Laravel has made it trivial so far to utilize the queues.. I am almost done putting it all together.

BTW thanks for the kickass package my friend!

**Comment by franzose** [comment]
@moebaca You're welcome! If you have any other issue, please open a new ticket. I will not close this one for a while.

**Comment by moebaca** [comment]
Thanks! I do like the sound of the feature. I am stuck on Laravel 5.1 for the foreseeable future.. though I may try and migrate to 5.5 since Taylor mentioned it would be LTS. 

Thanks again.
