### ISSUE TITLE
Use closure on User Authenticate

### ISSUE THREAD

**Issue by AngryElephant** [franzose/ClosureTable#177]
I need to use closure on the builtin Laravel Auth which extend Authenticate. How can o use this package on it ?

**Comment by franzose** [comment]
How do you want to use closure tables?

**Comment by AngryElephant** [comment]
Each User can have Child user on 8 levels. like this and so on http://prntscr.com/bsoy64

**Comment by franzose** [comment]
@AngryElephant hmm, I would extend User from the standard Model and just repeat the setup from Authenticatable.

**Comment by AngryElephant** [comment]
How can i extend Entity in this case ?

**Comment by franzose** [comment]
@AngryElephant sorry, I was wrong. I'd extend User from _Entity_ but then repeated the setup from Authenticatable.

**Comment by AngryElephant** [comment]
So i just copy this https://github.com/laravel/framework/blob/4.2/src/Illuminate/Auth/UserTrait.php  in my App model ? 

Thank you.

**Comment by franzose** [comment]
I think you need this:

```php
class User extends Entity implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
}
```

**Comment by AngryElephant** [comment]
I got this error App\user cannot use Illuminate\Foundation\Auth\User - it is not a trait

**Comment by AngryElephant** [comment]
i managed it. Thank you.

**Comment by franzose** [comment]
@AngryElephant Could you paste here your solution?

**Comment by AngryElephant** [comment]
sure, this is the User model:

namespace App;

use Franzose\ClosureTable\Models\Entity;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class user extends Entity implements 
  AuthenticatableContract,
  AuthorizableContract,
  CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
    /**
     * The table associated with the model.
     *
     * @var string
     */

    protected $fillable = [
        'email', 'password', 'name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    protected $table = 'users';

    /**
     * ClosureTable model instance.
     *
     * @var userClosure
     */
    protected $closure = 'App\userClosure';
}
