### ISSUE TITLE
Get all children from given level ? 

### ISSUE THREAD

**Issue by AngryElephant** [franzose/ClosureTable#179]
How can i do if i want to get all children on level 2 ? 

 (example: http://image.prntscr.com/image/32d056f0e4124ba9b0a6cf69253083cf.png)

**Comment by coreysan** [comment]
@AngryElephant, you should read the docs a couple times over. 

Each node in the tree has a `real_depth` property, so you can query for children with something like: 
`YourEntity::where('real_depth', 2)->get()`

**Comment by ipcoleman** [comment]
@coreysan @AngryElephant This would get you every entity at level 2, regardless of root. I suspect that would be undesired behavior. If you want to get children of a specific root at level 2 , you could do:

`$root->getDescendants()->where('real_depth', 2);`

**Comment by coreysan** [comment]
Nice one @ipcoleman :)
