### ISSUE TITLE
Iterate through getDescendantsTree() collection ? 

### ISSUE THREAD

**Issue by AngryElephant** [franzose/ClosureTable#180]
getDescendantsTree() return me a nested collection but i only want to get the Descendant tree with a max depth of 6.

I Tried the reject: 

    $test = $user->getDescendantsTree()->reject(function($item){return $item->depth < 6 ;});

But no results. I also tried map(), each ... But i only get the first user.

Any suggestion ? 

Thank you.

**Comment by AngryElephant** [comment]
Any idea ?

**Comment by franzose** [comment]
@AngryElephant Hi. The package uses custom eloquent collection that has method called `toTree`. So you can query like this:

```php
$user->getDescendantsWhere(...)->toTree();
```

**Comment by AngryElephant** [comment]
Thank you for your answer. I got this error :

     $tree = $user->getDescendantsWhere('depth' < 6 )->toTree();

Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '1' in 'where clause' (SQL: select * from `users` inner join `user_closure` on `user_closure`.`descendant` = `users`.`id` where `user_closure`.`ancestor` = 2 and `user_closure`.`depth` > 0 and `1` is null)'

**Comment by AngryElephant** [comment]
To make it simple, is there any way to get the descendant tree on a max depth of 6 ?

**Comment by AngryElephant** [comment]
Sorry, looks like 

    $tree = $user->getDescendantsWhere('depth','<' ,5)->totree();

Made the thing :) Thank you.

**Comment by franzose** [comment]
@AngryElephant You're welcome)

**Comment by AngryElephant** [comment]
I passed the $tree to my view but i still can display only 1 result 

    @foreach ($tree as $member)
        <p>{{ $member->name  }}</p>
    @endforeach

How can i iterate and display all of children ?

**Comment by AngryElephant** [comment]
This is the solution 

    function makeNestedList(array $Array){

    	$Output = '<ul>';
    	foreach($Array as $Key => $Value){
    		$Output .= "<li><strong>{$Key}: </strong>";
    		if(is_array($Value)){
    			$Output .= $this->makeNestedList($Value);
    		}else{
    			$Output .= $Value;
    		}
    		$Output .= '</li>';
    	}
    	$Output .= '</ul>';
    	return $Output;
    }

**Comment by AngryElephant** [comment]
Any way to include use current  user on 
    $tree = $user->getDescendantsWhere('depth','<' ,6)->totree();

?

**Comment by franzose** [comment]
@AngryElephant it's more complex task, so you can write your own method using `protected function joinClosureBy($column, $withSelf = false)` method and setting its second argument to `true`.

**Comment by AngryElephant** [comment]
Yes i made a new array with the current user info and pass the $tree as children.

Thank you.

**Comment by franzose** [comment]
@AngryElephant cheers!
