### ISSUE TITLE
Laravel 5.3 support

### ISSUE THREAD

**Issue by n5a45m7** [franzose/ClosureTable#181]
According to https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0
Method **lists** on the Collection, query builder and Eloquent query builder objects, which was marked as deprecated in 5.2 version, was removed. Should used method **pluck** instead with same signature.

There is only one occurence of method **lists** in code:
/src/Franzose/ClosureTable/Models/Entity.php line 1433

Just need to rename **lists** to **pluck.**

All other code looks like working correct with Laravel 5.3

Thanks!

**Comment by franzose** [comment]
@n5a45m7 I have made the changes as you requested!
