### ISSUE TITLE
Get entities on the same level  

### ISSUE THREAD

**Issue by seuaCoder** [franzose/ClosureTable#182]
Hi,

on the schema http://image.prntscr.com/image/734031da1d7c454bbebc78aada981eac.png  i have the  item 7 id, i would like to get all entities on the same level : 4 5 6.

Is there any easy way to do this without hitting the db too hard ?

Thank you and congrats for this great library.

**Comment by franzose** [comment]
Hi, @seuaCoder! I think you can use `Entity::getPrevSiblings()` or `Entity::getSiblingsRange($from, $to)` if you want more precise result.

**Comment by seuaCoder** [comment]
Hey @franzose ,

I tried getPrevSiblings() but it gets the entities which have the same parent , only 6 on the example. What if i need 4 5 6  ? 

I'm thinking to use the real_depth  of 7 and get all the entities with the same real depth. 

I actually need to find enpty places, entities without children so i need to get all the entities with the same real_depth then use a loop to check all of them with getChildAt().

It looks really expensive but i don't find any other solutions.

**Comment by seuaCoder** [comment]
Also would like to know if it's possible to get the "real position" of the entities on the same depth from left to right. currently the position column is related to the parent.

**Comment by franzose** [comment]
@seuaCoder I'm sorry, I viewed the diagram inattentively. Using `real_depth` you can get all entities of the same level. And to find out whether an entity is a leaf you need to count its children. I think a query for a leaf itself would be something like `select case when count(descendant) = 0 then 1 else 0 from closure_table where ancestor = <ID>`. So, you need to combine `real_depth` and leaf queries in one.

**Comment by seuaCoder** [comment]
Thank you. Managed with `real_depth` column.

**Comment by franzose** [comment]
@seuaCoder, cheers! Also, it would be great if you paste your solution here for those who's trying to solve a similar task as yours.

**Comment by seuaCoder** [comment]
sure. To get all user on same level :

    $users = User::where('real_depth', $user->real_depth) ->orderBy('id', 'ASC')->get();

I order by id ASC to get the right position order. Then i check each user to see if they have less than 2  children, if they have less than 2 children, if so i break the loop:

    foreach ($parents as $parent) { 

            if ($parent->countChildren() < 2) {

               // do something

                break;  
            }

        }
