### ISSUE TITLE
Hierarchical entity with relation

### ISSUE THREAD

**Issue by altercode** [franzose/ClosureTable#183]
Hi,

In my app i would like to do this:

`Category::with('CategoryTranslation')->getTree();`

but i get 

`Call to undefined method Franzose\ClosureTable\Extensions\QueryBuilder::getTree()`

Is there a possibility to use closuretable with other relations?

Thanks in advanced!

**Comment by franzose** [comment]
Hi! Obviously, QueryBuilder is not capable to create tree. You can set `$with` array in you model.

**Comment by zvermafia** [comment]
Hi, @franzose!

I have a similar problem. I'd like to get root categories with a relation products and with a condition. So I tried:
```php
Categories::whereHas('products', function ($query) {
    $query->where('status', 'active');
})->getRoots();
```
But I get error:
```
Call to undefined method Franzose\ClosureTable\Extensions\QueryBuilder::getRoots()
```
I saw you told about `$with` property of the model, but I don't understand how can I use it in my case. Can you explain?

**Comment by zvermafia** [comment]
Until I do like this:
```php
Categories::whereHas('products', function ($query) {
   $query->where('status', 'active');
})->whereNull('parent_id')->get(['*']);
```
Does the package have a more beautiful way?

**Comment by franzose** [comment]
@zvermafia Hi! Unfortunately, as of now, the package is not capable to solve such tasks.
