### ISSUE TITLE
Laravel 5.4 compatible but error in 5.3

### ISSUE THREAD

**Issue by duongtdvn** [franzose/ClosureTable#188]
@franzose this trait `Illuminate\Console\DetectsApplicationNamespace` used in the recent released version 4.1.5 which does not available in laravel 5.3. Could you please take a look?

**Comment by franzose** [comment]
@duongtdvn You have to use L5.3 branch: https://github.com/franzose/ClosureTable/tree/L5.3. Master is always for the actual stable Laravel version, I'm sorry.

**Comment by duongtdvn** [comment]
I see, it is because of the L5.3 branch also contain the 4.1.5 tagged in release and while including `"franzose/closure-table": "4.*"` in `composer.json` it will also upgrade to the latest release.
My suggest is to lock the 4.x version to support only laravel 5.3 and lower then create a new major version 5.x for supporting laravel >=5.4?

**Comment by franzose** [comment]
@duongtdvn I have removed tag `v4.1.5` and changed the latest release to `v5.0`. Hope it'll solve problems.

**Comment by Chaddles23** [comment]
Please remove v4.1.5 from Packagist
https://packagist.org/packages/franzose/closure-table#v4.1.5

**Comment by franzose** [comment]
@Chaddles23 Done!
