### ISSUE TITLE
Ошибка FatalErrorException in Cat.php line 6: Interface 'App\catInterface' not found

### ISSUE THREAD

**Issue by roduman** [franzose/ClosureTable#189]
На локальном компьютере решение настроил, все работает отлично, при переносе на хостинг выдается ошибка 

FatalErrorException in Cat.php line 6:
Interface 'App\catInterface' not found

С чем это может быть связано. Спасибо.

**Comment by franzose** [comment]
Возможно, причина в том, что название интерфейса должно начинаться с большой буквы, т.е. `App\CatInterface`.

**Comment by roduman** [comment]
Когда мы выполняем команду - php artisan closuretable:make --entity=page

После --entity=, Page записываем с большой буквы, ведь так, видимо в этом была моя ошибка?

**Comment by franzose** [comment]
@roduman, скорее всего да.
