### ISSUE TITLE
Removing a parent node and re-attaching another node as parent messes up the `real_depth` column

### ISSUE THREAD

**Issue by kfirba** [franzose/ClosureTable#190]
**Version: master (v5)**

Hey.

Given the following categories structure:

```
Root - real_depth 0
    CategoryA  - real_depth 1
        SubCategoryA  - real_depth 2
        SubCategoryB  - real_depth 2
```

If we remove the `Root` category, by default, the tree changes to:

```
CategoryA - real_depth 1
    SubCategoryA - real_depth 2
    SubCategoryB - real_depth 2
```

As you can see, the children nodes did not update their `real_depth` value. The issue is if I now add a new root category, the `real_depth` is only getting worse:

```
NewRoot - real_depth 0
    CategoryA  - real_depth 1
        SubCategoryA  - real_depth 3
        SubCategoryB  - real_depth 3
```

Note that the direct child (`CategoryA`) has updated its `real_depth` value to the correct one, however, its children (`SubCategoryA`, `SubCategoryB`) thought they were pushed 1 level deeper and their `real_depth` is now 3. If we repeat the process of deleting the root category and re-adding a new root category, you will see that the `real_depth` will continue to go "deeper" and increment to 4,5,6 etc.

# Solution
As I see it, there are 2 ways to deal with this:

1. **Not really a solution** - Set the `onDelete` constraint to `cascade` instead of `null` which will simply remove the whole tree and this will bypass the problem.
2. **Best solution** - Keep the current behavior where the node's `real_depth` property is keeping incrementing and **ensure** that when we delete a parent node, we decrease the `real_depth` of its descendants by 1. This will cause the tree to look something like that after deletion:

    ```
    CategoryA - real_depth 0
        SubCategoryA - real_depth 1
        SubCategoryB - real_depth 1
    ```
    As you can see, after deleting a root node, we actually get a correct new tree.

What do you think?

**Comment by arrowdesign** [comment]
Thanks for reporting kfirba i got the same issue with 5.1 and also had problems that the ancestor chain broke. I did a quick fix and my problems are solved.

    public function moveTo($position, $ancestor = null)
    {
        $parentId = (!$ancestor instanceof EntityInterface ? $ancestor : $ancestor->getKey());
        if ($this->parent_id == $parentId && !is_null($this->parent_id)) {
	        if (isset($ancestor))
	        {
		        $this->real_depth = $this->getNewRealDepth($ancestor);		        
			$this->isMoved = true;
			$this->save();
			$this->isMoved = false;				
	        }

            return $this;
        }

        if ($this->getKey() == $parentId) {
            throw new \InvalidArgumentException('Target entity is equal to the sender.');
        }

**Comment by franzose** [comment]
@arrowdesign Could you submit a PR with these changes and tests for them?

**Comment by franzose** [comment]
Sorry if it's inconvenient, but I just deprecated `real_depth`.
