### ISSUE TITLE
ClosureTable SQL not compatible with MS SQL Server

### ISSUE THREAD

**Issue by arminlinder** [franzose/ClosureTable#192]
I followed your installation instructions and tried to create the tables for a "pages" model to test the component.
`php artisan closuretable:make --entity=page`
runs. But trying to run
`php artisan migrate`
fails with the following error:
>  [Illuminate\Database\QueryException]
 SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Introducing FOREIGN KEY constraint 'pages_parent_id_foreign' on table 'pages' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
(SQL: alter table "pages" add constraint "pages_parent_id_foreign" foreign key ("parent_id") references "pages" ("id") on delete set null)

A similar problem has been described here:
[http://stackoverflow.com/questions/851625/foreign-key-constraint-may-cause-cycles-or-multiple-cascade-paths](url)

Database experts to the rescue, please advise how I can deal with this problem.

Armin.

**Comment by franzose** [comment]
@arminlinder, I think you should tweak generated migration files to meet the requirements of the MS SQL Server.
