### ISSUE TITLE
I want to use getQualifiedKeyName when call function Entity#deleteSubtree

### ISSUE THREAD

**Issue by sh-ogawa** [franzose/ClosureTable#193]
My System's tree table used 'id' column.
So call to deleteSubtree and throw exeception.

It is difficult to change the database design.
So pluck argument changes '$this->getKeyName()' to '$this->getQualifiedKeyName()' .

**Comment by franzose** [comment]
@sh-ogawa Hi, I have just merged your changes!

**Comment by sh-ogawa** [comment]
Thank you!
I comfirm this and close.
