### ISSUE TITLE
Installation instructions outdated

### ISSUE THREAD

**Issue by arminlinder** [franzose/ClosureTable#195]
Not a big issue, but the installation instructions given will always install a version 4, which won't work with Laravel version 5. It is also quite unclear how the different versions for Laravel 5.1, 5.2 ect. need to be addressed.

Same is true für the instructions given on how to register the provider, since in L5 the file paths have been changed.

I suggest to change the installation instructions to be version-neutral, or update it so it reflects the current Laravel version 5.

**Comment by franzose** [comment]
@arminlinder Can you submit a PR with the changes?
