### ISSUE TITLE
Migration won't run due to interchanged migration files

### ISSUE THREAD

**Issue by arminlinder** [franzose/ClosureTable#196]
After creating the model, like described in the instructions, when running 

`php artisan migrate`

the migration crashes with the following errors (actual text may vary slightly, I tried to translate from German):

```
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server] The page_closure_ancestor_foreign- foregn key references the invalid pages-tale. (SQL: alter table "page_closure" add constraint "page_closure_ancestor_foreign" foreign key ("ancestor") references "pages" ("id"))

  [PDOException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The page_closure_ancestor_foreign- foreign key references the invalid pages-table.
```

Cause is, that the migrations .php files put into the database\migrations directory are in incorrect order:

`2017_07_24_080809_create_page_closures_table.php`
`2017_07_24_080809_create_pages_table.php`

Since the prefix files (2017_07_24_080809_create_...) are identical, the closures_table will always run first,  this causes the error because you cannot create a foreign key refefencing a non existent table. To change the order, I renamed the create_pages_table file

`2017_07_24_080808_create_pages_table.php`
`2017_07_24_080809_create_page_closures_table.php`

and the migrations worked.

An even better approach would be, in my opinion, to use one single migration file to set up both tables.

**Comment by franzose** [comment]
@arminlinder I merged generated migrations into a single file. Needs testing though.

**Comment by franzose** [comment]
@arminlinder, if succeeds I will make a new release.

**Comment by arminlinder** [comment]
Thanks! I'll give it a try, and let you know about my findings.

Thumbs up, Armin.

**Comment by arminlinder** [comment]
**ClosureTree is broken**
Not sure whether this change broke the component, but from the behaviour I experience I'd bet it did. I am fairly sure that this change broke the migration file generator. My environment: Windows Server 2012 R2, PHP 7.1.1, Laravel 5.4, MS SQL Server 2012.

In short: the migration file created is invalid (see attachment). Theory: instead of the intended php code, the file name gets written into the file.

The long story:
I tried to include closureTable into a new project a few days ago, and failed to initialize the closure databases. To narrow the problem I set up an entirely fresh project today. All I have to do to reproduce the problem (tried twice) is create aN entirely new  project, in an empty directory.
```
laravel new
```
then a 
```
composer require franzose\closureTable "*"`
```
which does correctly pull in a version 5.1. Then
```
php artisan closuretable:make --entity=page
```
gives the following responses, still looking allright:
```
create  2017_09_18_135017_create_pages_table
create  Page
create  PageInterface
create  PageClosure
create  PageClosureInterface
```
but in the next step, when I initialize the databases using
```
php artisan migrate
```
this bangs out with error:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'CreatePagesTable' not found
```
If I look into the migration file, it is obviously invalid (see attched file too). The contents is only
```
migrations/2017_09_18_135017_create_migrations_table.php
```
Can you reproduce the problem in your environment & fix?
Best regards from Bavaria, Armin.
[2017_09_18_135017_create_pages_table.php.txt](https://github.com/franzose/ClosureTable/files/1310949/2017_09_18_135017_create_pages_table.php.txt)

**Comment by arminlinder** [comment]
oops, saw another possible cause: "Laravel new" does now install 5.5.4. Could be a compatibility issue with the new Laravel version as well ...

Btw, can I re-open this issue, or should I create a fresh one, Please advise!

Armin.
