### ISSUE TITLE
moveTo does not recalculate position if move is on same level

### ISSUE THREAD

**Issue by arminlinder** [franzose/ClosureTable#203]
I need to reorder nodes. The code I have is as follows

$n=node to move, current node
$t = node to move to, target node
$position = 'inside' --> make $n a new child node of $t
$position = 'after' --> make $n a sibling after $t
$position = 'before' --> make $n a sibling before $t (not used yet)

```
            switch ($position) {
                case 'inside':  // add new child at position 0
                    $n->moveTo(0,$t->id);
                    break;
                case 'after':  // add sibling behind target node
                    $pId = $t->parent_id;
                    $n->moveTo($t->position + 1,$pId);
                    break;
                default:throw new Exception("Invalid position: $position");
            }
```
The code works, except when $n and $t are on the same level (i.e. have the same parent node). If so, moveTo silently fails, i.e. does nothing.

Or, the other way round, moveTo a new position works only, if the parent node is changed as well.

To work around the issue, I tried:

```
                case 'after':  // add sibling behind target node
                    if ($n->parent_id = $t->parent_id) {    // move on same level
                        $n->position = $t->position + 1;
                        $n->save();
                    } else {
                        $n->moveTo($t->position + 1,$t->parent_id);
                    }
                    break;
```
this seems to work most of the time, but I am not sure whether it does always work, and this is the way I am supposed to do a position move. Is it?

Best regards,

Armin.

**Comment by franzose** [comment]
@arminlinder, sorry for not answering you. If you want to rearrange items of the same nesting level, use just `$item->position = <new position>;`, and use `$item->moveTo()` otherwise.
