### ISSUE TITLE
Most Effective Use of Storing Deep, Redundant Hierarchies

### ISSUE THREAD

**Issue by moebaca** [franzose/ClosureTable#206]
Hello,

I am seeking help on a problem I've been working using this library for about a year now.

I am allowing users to store Bill of Materials (basically giant parts hierarchies) using this library and the performance as the tables grow (now at 800k+ records in the closure table) is starting to sag.

Basically a user needs to add a part anywhere in the hierachy and anywhere else that part is stored in any other hierarchy needs to be updated as well. For example, you have a screw part that you put under a server part, this server might be in 20 other assemblies and therefore needs to have the screw part added underneath it in those other 19 places. 

Basically I only allow one transaction to take place at a time and they are queued so that no two users are updating the tables at once. This works great so far. What I do is a query the parts in the database that have the part number of the server in this example, loop through and do a "createFromArray" library method on the JSON that I've formatted that are shipped from the client side, then I loop through and add each child with the "addChild" function to the part. 

Here is a snip of the code:

```php
// Get All Instances of Part Number for Updating
$root_dependencies = LPartNumbersHierarchy::where('PartNumber_ID', '=', $root_part_number_id)->get();

foreach ($root_dependencies as $root_dependency){
            $entity = LPartNumbersHierarchy::find($root_dependency->id);

            // Mass Create Children Nodes
            $new_children = LPartNumbersHierarchy::createFromArray($tree);

            // Add Each Child "Root" (This will carry its children too so no need to go recursive) to the Parent
            foreach ($new_children as $new_child) {
                $entity->addChild($new_child);
            }
}
```

Maybe I could use different, more performant functions in the library? Maybe I could look at structuring the data differently to reduce all of the redundancy? Say, store the hierarchy for each part once and then just reference that part in all the places it needs to be? I don't know how I'd go about doing that though, especially with this library.

Any advice on a more efficient approach would greatly be appreciated. It can take several minutes just to add a few parts to a tree that are in 1 or 2 other places at this point... 

We've tweaked the MySQL settings to try and use more memory.. whenever I run one of these updates to a BOM tree it basically revs a single core to 100% on the database server for the whole duration. I wish that MySQL would leverage more than that single core, but yeah its maxing out that core for the whole duration of the update.

**Comment by franzose** [comment]
@moebaca I would took out `find` outside the loop. Something like this:

```php
// Get All Instances of Part Number for Updating
$deps = LPartNumbersHierarchy::where('PartNumber_ID', '=', $root_part_number_id)->get();
$depIds = $deps->map(function ($dep) {
    return $dep->id;
});

// Find all entities at once
$entities = LPartNumbersHierarchy::findByIds($depIds); 

// Where does the $tree come from?
$children = LPartNumbersHierarchy::createFromArray($tree);

foreach ($entities as $entity) {
    foreach ($children as $child) {
        $entity->addChild($child);
    }
}
```

I don't know your specifics but any large amount of objects will blow up the memory...

**Comment by moebaca** [comment]
Thank you for the response. I will go ahead and give her another look with your suggestions. I definitely figured it probably wasn't anything that could be helped much more because I am indeed doing A LOT of calculations. My users always try and make their requirements the most complicated as possible just for me.. they really love me. I think its at a more acceptable level now that I've also tuned MySQL to use more memory and gave the server more memory. I've also done a few other tiny tweaks. If she complains again I am going to straight up make my queued job split off each update into their own jobs so that I can have MySQL leverage more than a single core per update.. 

Anyways I will mark this closed. Thanks for the response and everything!
