### ISSUE TITLE
ClosureTable and SoftDelete support

### ISSUE THREAD

**Issue by arminlinder** [franzose/ClosureTable#207]
Can I use SoftDeletes() in the Items and Item_closure databases? If so, how do I call query functions like GetDescendants(), so I do get

a) all Items but the softdeleted ones
b) all items including the softdeleted ones

Thx!

**Comment by arminlinder** [comment]
Seems Closuretree does not support SoftDelete at all.

**Comment by arminlinder** [comment]
IMHO it should.

**Comment by franzose** [comment]
Hi. I'm sorry for not responding to you. Soft-delete itself has always been supported by the library but there were no easy way to query soft-deleted items out-of-the-box. I've just made [a new release](https://github.com/franzose/ClosureTable/releases/tag/v6.0). I think that now you can do something like this:

```php
Node::descendants()->withTrashed()->get();
```

Where `withTrashed` is the Laravel's built-in query scope.
