### ISSUE TITLE
Not working in Laravel5.6

### ISSUE THREAD

**Issue by tonila** [franzose/ClosureTable#208]
I was not sure, what version to install, so I just 

```
composer require franzose/closure-table
```

It installled closure-table ^5.1. 

Then I run:

```
$ php artisan closuretable:make --entity=page
      create  2018_06_12_053446_create_pages_table
      create  Page
      create  PageInterface
      create  PageClosure
      create  PageClosureInterface
```

And then:

```
php artisan migrate
```
Which throws exception:
"Class 'CreatePagesTable' not found"

PHP v7.2

**Comment by moebaca** [comment]
Did you open up 2018_06_12_053446_create_pages_table and verify that the name of that class is CreatePagesTable? 

IIRC, even when I installed the package on 5.1 a year or so ago I had to fiddle with some of the files that were generated to get it running.
