### ISSUE TITLE
--models-path=app/Models namespace issue

### ISSUE THREAD

**Issue by alinmiron** [franzose/ClosureTable#213]
Hi @franzose, 
I've ran this command to put the Models in the custom folder.
 php artisan closuretable:make --models-path=app/Models --entity  taxonomies
The model files are put in the specific custom location but internally, their namespaces are wrong: They are still
 namespace App;
instead of 
namespace App\Models;
For now, I've changed them manually in my project. 
Can you check?
Thanks!

**Comment by franzose** [comment]
Hi, @alinmiron. I'm not sure this is still relevant to you at all but just for you to know: `--models-path` option has never affected the namespace because there's a dedicated option for that, `--namespace`.
