### ISSUE TITLE
How I use only ClosureTable without parent_id, position, real_depth in entity table?

### ISSUE THREAD

**Issue by devig** [franzose/ClosureTable#215]
How I use only ClosureTable without parent_id, position, real_depth in entity table or without real_depth, at least?
(In russian: Как мне использовать только ClosureTable без колонок parent_id, position, real_depth в таблице основной сущности или хотя бы без real_depth?)

**Comment by franzose** [comment]
Due to the implementation, you cannot use pure closure table with this library.
