### ISSUE TITLE
 Call to undefined method Illuminate\Foundation\Application::share() 

### ISSUE THREAD

**Issue by atefeh21** [franzose/ClosureTable#216]
Hello,
I'm using laravel 5.7 and when I installed the package I've got this error:

 Call to undefined method Illuminate\Foundation\Application::share()

**Comment by miguelurbina** [comment]
Hello,

You should use the version 5.1.1 insteadof 4.*, put this in your composer.json:

  "franzose/closure-table": "5.1.1",

Then, composer update in terminal.
