### ISSUE TITLE
Compatibility with later Laravel versions (5.7, 5.8 and 6.x)

### ISSUE THREAD

**Issue by nilserikm** [franzose/ClosureTable#222]
Does anyone know if this library is compatible with later Laravel version, specifically 5.7, 5.8, and 6.x?

We are currently using this library and we are looking to upgrade our Laravel versions, hence the question.

Any feedback would be appreciated.

**Comment by ottosmops** [comment]
We used the package with L 5.7, 5.8 and 6.x We had not problems.

**Comment by manveloff** [comment]
> We used the package with L 5.7, 5.8 and 6.x We had not problems.

Thank you for the info.

**Comment by franzose** [comment]
I'm sorry for silence. I haven't tested the package on newer versions of Laravel. I hope to do that in the near future.

**Comment by avvertix** [comment]
I also used the package on Laravel 5.7, but I can't confirm if is compatible with newer versions. I'm also interested in knowing about Laravel 6.x compatibility.

I saw that there is Travis CI configured, but the pipelines are failing. I would like to help by submitting a pull request that tries ensure Travis CI tests are at least running.

**Comment by franzose** [comment]
Many many thanks to @avvertix, he made an excellent job to set up Travis CI properly. I suppose we're pretty sure now that the library supports Laravel 5.4+ including 6 and 7.
