### ISSUE TITLE
Collection::makeTree() hits database for each child

### ISSUE THREAD

**Issue by ritterg** [franzose/ClosureTable#231]
I use ->getDescendants()->toTree() to get the whole tree and show it as a hierarchical list of checkboxes.
Up to version 5.1.1 this was one database hit (to get descendants).
`select * from `terms` inner join `term_closure` on `term_closure`.`descendant` = `terms`.`id` where `term_closure`.`ancestor` = 1 and `term_closure`.`depth` > 0`

In version 6 it is now one database hit (to get descendants, same as above) and one database hit for each child
`select * from `terms` where `terms`.`parent_id` = 2 and `terms`.`parent_id` is not null`

This makes building a larger tree very slow.

The problem seems to be on line 174 of Collection.php:
`$result[$parentId]->children->add($item);`
which used to be (in 5.1.1, Collection.php line 80)
`$result[$parentId]->appendRelation($item->getChildrenRelationIndex(), $item);`

Is there a way to get the tree without all these database hits?

**Comment by ritterg** [comment]
I was able to improve the speed of ->toTree() by loading the children relation on the descendants collection before calling toTree().

So instead of
$root->getDescendants()->toTree()
I do
$descendants = $root->getDescendants();
$descendants->load('children');
$tree = $descendants->toTree();

Still not as good as it was in 5.1.1, but much better than without loading children (now 2 database queries instead of 1 + (number of descendants))

**Comment by franzose** [comment]
Hello, @ritterg! It seems it's a regression :/ I'm going to fix it and make a new release.

**Comment by ritterg** [comment]
I can confirm that this (Version 6.0.1) fixes my issue.
Thanks for the quick fix.

**Comment by franzose** [comment]
You're welcome!
