### ISSUE TITLE
Examples from readme are not works

### ISSUE THREAD

**Issue by devig** [franzose/ClosureTable#234]
Laravel 7, php 7.4.5, Mysql 8 
1)
$nodes = [
    new Node(['id' => 1]),
    new Node(['id' => 2, 'parent_id' => 1]),
    new Node(['id' => 3, 'parent_id' => 2]),
    new Node(['id' => 4, 'parent_id' => 3])
];
...
Result for the default structure: **parent_id null for all rows !**
(Поле parent_id null после вставки  для всех столцов)
------
2)
Node::createFromArray([
    'id' => 1,
    'children' => [
        ['id' => 2],
        ['id' => 3],
        ['id' => 4],
        ['id' => 5],
        [
            'id' => 6,
            'children' => [
                ['id' => 7],
                ['id' => 8],
            ]
        ],
    ]
]);
...
Error: **array_key_exists() expects parameter 2 to be array, int given**

---------
3) For the case if you wanna to change columns names
this 

    private function selectRowsToInsert($ancestorId, $descendantId)
    {
        $table = $this->getPrefixedTable();
        $ancestor = $this->getAncestorColumn();
        $descendant = $this->getDescendantColumn();
        $depth = $this->getDepthColumn();

        $select = "
            SELECT tbl.{$ancestor} AS ancestor, ? AS descendant, tbl.{$depth}+1 AS depth
            FROM {$table} AS tbl
            WHERE tbl.{$descendant} = ?
            UNION ALL
            SELECT ? AS ancestor, ? AS descendant, 0 AS depth
        ";

Should be like this
 private function selectRowsToInsert($ancestorId, $descendantId)
    {
        $table = $this->getPrefixedTable();
        $ancestor = $this->getAncestorColumn();
        $descendant = $this->getDescendantColumn();
        $depth = $this->getDepthColumn();

        $select = "
            SELECT tbl.{$ancestor} AS {$ancestor}, ? AS {$descendant}, tbl.{$depth}+1 AS {$depth}
            FROM {$table} AS tbl
            WHERE tbl.{$descendant} = ?
            UNION ALL
            SELECT ? AS {$ancestor}, ? AS {$descendant}, 0 AS {$depth}

Becouse It's just hardcode) 
(названия столбцов ancestor, ? AS descendant, 0 AS depth - просто захардкоджены)

**Comment by franzose** [comment]
Hi, @devig! I'm sorry for not answering you. I'm going to investigate the described issues soon.

**Comment by franzose** [comment]
I checked the first case (created entities in the loop) and everything went well. So, I'm closing the issue.
