### ISSUE TITLE
Child with multiple parents not possible (child will be moved)

### ISSUE THREAD

**Issue by albertatnerdbrain** [franzose/ClosureTable#235]
Hello,

I have different trees, but they can be connected to each other. So it could be possible, that one child can be connected to a parent in tree A and a parent in tree B 

But the addChild method moves the connection instead of add one.

My question: Is there any solution for me?

**Comment by franzose** [comment]
Hi, @albertatnerdbrain. I'm sorry for not answering. The `addChild` method's behavior is intentional. I think you're better to implement the custom functionality by yourself.
